// docs/swaggerDef.ts
export const swaggerDefinition = {
  openapi: "3.0.0",
  info: {
    title: "Book Management API",
    version: "1.0.0",
    description: "RESTful CRUD สำหรับจัดการหนังสือ",
  },
  servers: [{ url: "http://localhost:5000", description: "Local server" }],
  components: {
    schemas: {
      Book: {
        type: "object",
        properties: {
          id: { type: "integer" },
          title: { type: "string" },
          author: { type: "string" },
          published_year: { type: "integer", nullable: true },
          genre: { type: "string", nullable: true },
          created_at: { type: "string" },
          updated_at: { type: "string" },
        },
      },
      BookInput: {
        type: "object",
        required: ["title", "author"],
        properties: {
          title: { type: "string" },
          author: { type: "string" },
          published_year: { type: "integer", nullable: true },
          genre: { type: "string", nullable: true },
        },
      },
      SimpleBook: {
        type: "object",
        properties: {
          id: { type: "integer" },
          title: { type: "string" },
        },
      },
      Error: {
        type: "object",
        properties: {
          error: { type: "string" },
        },
      },
    },
    responses: {
      NotFound: {
        description: "Route not found",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
          },
        },
      },
      InternalError: {
        description: "Internal Server Error",
        content: {
          "application/json": {
            schema: { $ref: "#/components/schemas/Error" },
          },
        },
      },
    },
  },
};
