# .github/workflows/ci.yml
name: CI – Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # --- ฝั่ง client ---
      - name: Install & Build client
        working-directory: ./client
        run: |
          npm ci
          npm run build

      - name: Test client
        working-directory: ./client
        run: npm test

      # --- ฝั่ง server ---
      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Run server tests
        working-directory: ./server
        run: npm test
